name: social_media_fyp
description: "NexusConnect - A futuristic social media application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0

  # Animations
  flutter_animate: ^4.3.0
  shimmer: ^3.0.0

  # UI Blur Effects
  flutter_blur: ^0.0.2

  # State Management
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
